import { ISOString } from '@shared';

/**
 * These values should not be defined in `config.json`
 * as they are automatically generated.
 *
 * If provided, they will overwrite the default ones.
 */
export interface AutoGeneratedConfig {
    /**
     * Commit hash of current server version.
     *
     * This can be `unknown` if not `.git` directory is found.
     */
    commit: string;

    startedAt: ISOString;
}
