import { UserService } from '../../services';
import { AutoGeneratedConfig } from '../../types/Config';
import { AuthScope, EndpointProvider } from '../../types/Express';
import { ISOString } from '../../types/Utility';

interface PostRootResponse extends AutoGeneratedConfig {
    receivedRequest: ISOString;
    sentResponse: ISOString;
    numUsersTotal: number;
    numUsersActive: number;
    numGames: number;
}

export const postRoot: EndpointProvider<
    AuthScope.None,
    void,
    PostRootResponse
> = {
    authScope: AuthScope.None,
    async handler({ config, userModel, res }) {
        const receivedRequest = new Date().toISOString();

        const numUsersTotal = await UserService.countUsers(userModel);

        const numUsersActive = 0;
        const numGames = 0;

        const { startedAt, commit } = config;

        res.status(200).json({
            commit,
            startedAt,
            receivedRequest,
            sentResponse: new Date().toISOString(),
            numUsersTotal,
            numUsersActive,
            numGames,
        });
    },
};
