name: Deploy (Server)

on:
    workflow_run:
        workflows: ['CI (server)']
        types: [completed]
        branches: [main]

jobs:
    production-deploy:
        name: Deploy to Production
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        concurrency: production_deploy_server
        steps:
            - name: Execute remote script
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/Mafia/server
                      chmod +x scripts/deploy.sh
                      ./scripts/deploy.sh
