name: Deploy (Client)

on:
  workflow_run:
    workflows: ['CI (client)']
    types: [completed]

defaults:
    run:
        working-directory: client

jobs:
    production-deploy:
        name: Deploy to Production
        if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        concurrency: production_deploy_client
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8

            - name: Setup Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build static files
              run: pnpm build

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
                  directory: build
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  workingDirectory: client
